# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d9e211e3c1de63883b551585c11b2caad02d625be529cfa0dada41b1c9fce30dd3424ba005ca3fab54c89addb76d929b99e117e7a12cff694949162d0300cde

test:
  secret_key_base: ef2fb1fff0de7507cddbed9c713e87b4941630e4989c3773c92eb6941d78e3479ae4b838c2dfd3ad032b4cb7ab7b12cc2f40469854e5eb376618c63da73e31d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
